# Generated by Django 3.1.1 on 2020-10-13 01:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ponente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=30)),
                ('especialidad', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='aforo',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='ubicacion',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='evento',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='evento',
            name='ubicacion',
            field=models.CharField(max_length=80),
        ),
        migrations.AddField(
            model_name='turno',
            name='ponentes',
            field=models.ManyToManyField(to='eventos.Ponente'),
        ),
    ]
