# Generated by Django 3.1.1 on 2020-10-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20201012_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ponente',
            options={'ordering': ['apellido']},
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='aforo',
            field=models.IntegerField(default=40),
        ),
    ]
